[package]
name = "smeg-config"
version = "0.1.0"
edition = "2024"
authors = ["Pete Restall <pete@restall.net>"]

[dependencies]
smeg-config-procmacro = { path = "procmacro" }

[build-dependencies]
smeg-config-procmacro = { path = "procmacro" }
