use core::arch::asm;

use smeg_drivers_kernel_syscall::{SyscallInvocation, syscall_args};
use smeg_drivers_kernel_syscall::isr::{SyscallIsrContext, SyscallIsrHandler};
use smeg_kernel::interrupts::IsrContext;
use smeg_kernel::syscalls::SyscallResult;

// TODO: temporary blinky-blinky stuff, to verify syscall invocation on the Nucleo board...

// TODO: these are temporary (but correct layout), purely for the blinking LED...
#[repr(C, packed)]
#[allow(non_snake_case)]
struct RccRegisters {
    CR: u32,
    ICSCR: u32,
    CFGR: u32,
    PLLCFGR: u32,
    PLLSAI1CFGR: u32,
    _reserved_14: u32,
    CIER: u32,
    CIFR: u32,
    CICR: u32,
    _reserved_24: u32,
    AHB1RSTR: u32,
    AHB2RSTR: u32,
    AHB3RSTR: u32,
    _reserved_34: u32,
    APB1RSTR1: u32,
    APB1RSTR2: u32,
    APB2RSTR: u32,
    _reserved_44: u32,
    AHB1ENR: u32,
    AHB2ENR: u32,
    AHB3ENR: u32,
    _reserved_54: u32,
    APB1ENR1: u32,
    APB1ENR2: u32,
    APB2ENR: u32,
    _reserved_64: u32,
    AHB1SMENR: u32,
    AHB2SMENR: u32,
    AHB3SMENR: u32,
    _reserved_74: u32,
    APB1SMENR1: u32,
    APB1SMENR2: u32,
    APB2SMENR: u32,
    _reserved_84: u32,
    CCIPR: u32,
    _reserved_8c: u32,
    BDCR: u32,
    CSR: u32,
    CRRCR: u32,
    CCIPR2: u32
}

const _: () = assert!(core::mem::size_of::<RccRegisters>() == 0xa0, "RCC register bank must be 160 bytes (40 words)");

#[repr(C, packed)]
#[allow(non_snake_case)]
struct GpioRegisters {
    MODER: u32,
    OTYPER: u32,
    OSPEEDR: u32,
    PUPDR: u32,
    IDR: u32,
    ODR: u32,
    BSRR: u32,
    LCKR: u32,
    AFRL: u32,
    AFRH: u32,
    BRR: u32
}

const _: () = assert!(core::mem::size_of::<GpioRegisters>() == 0x2c, "GPIO register bank must be 44 bytes (11 words)");

unsafe extern "C" {
    unsafe static mut __LINKER_PERIPHERALS_AHB1_RCC: RccRegisters;
    unsafe static mut __LINKER_PERIPHERALS_AHB2_GPIOB: GpioRegisters;
}

pub trait Dependencies {
    type IsrContext: IsrContext;
}

pub trait Syscalls {
    type BlinkyBlinkySyscallHandler;
}

use core::marker::PhantomData;
pub struct Driver<D: Dependencies> {
    _dependencies: PhantomData<D>
}

impl<D: Dependencies> Driver<D> {
    pub const fn collect_isr_vectors<T>(isrs: T) -> T {
        isrs
    }
}

impl<D: Dependencies> Syscalls for Driver<D> {
    type BlinkyBlinkySyscallHandler = BlinkyBlinkySyscallHandler<D>;
}

// TODO: just a blinky-blinky to make sure the code links and runs properly on the Nucleo board.
#[unsafe(no_mangle)]
#[allow(static_mut_refs)]
pub extern "C" fn blinky_blinky() -> ! {
    // TODO: verify that the linker script gets the addresses right - because LLD differs from LD in some really horrible, subtle ways...
    if !core::ptr::addr_eq(&raw const __LINKER_PERIPHERALS_AHB1_RCC, 0x40021000 as *const u32) {
        panic!("Linker script for AHB1 RCC register is wrong");
    }

    if !core::ptr::addr_eq(&raw const __LINKER_PERIPHERALS_AHB2_GPIOB, 0x48000400 as *const u32) {
        panic!("Linker script for AHB2 GPIOB register is wrong");
    }

    unsafe {
        // Enable clocking of the GPIOB module
        let rcc_ahb2enr = &raw mut __LINKER_PERIPHERALS_AHB1_RCC.AHB2ENR;
        core::ptr::write_volatile(rcc_ahb2enr, 2);

        asm!(r#"
            nop
            nop
            nop
            nop
            nop
            nop
            nop
            nop
        "#);

        // Set LED pin to output
        let gpio_b_moder = &raw mut __LINKER_PERIPHERALS_AHB2_GPIOB.MODER;
        core::ptr::write_volatile(gpio_b_moder, 0xfffffe7f);

        let delay = 200000; // Debug builds now include some optimisations, but if not: if cfg!(debug_assertions) { 10000 } else { 200000 };
        let mut syscall = BlinkyBlinkySyscall { blink: 0 };
        loop {
            syscall.blink ^= 1;
            let result = syscall.invoke_syscall();
            if !result.is_ok() {
                smeg_kernel::despair!(with(smeg_kernel::errors::KernelErrorCode::GeneralDespair(0)), because("Syscall ISR returned non-OK value"));
            }

            for _ in 0..delay {
                asm!("nop");
            }
        }
    }
}





/*
TODO: When you revisit this, start from here.  Basically, now that there's a new structure (Driver<Dependencies>) facilitating better DI, we ought to be
able to do something about injecting the Syscall Driver as a dependency into, say, a BlinkyBlinky driver.  The Nucleo Board should be the place that wires
everything up (Composition Root).  By injecting the Syscall driver into BlinkyBlinky, BlinkyBlinky should be able to know the types for the 'SyscallContext',
trampolines generated by #[syscall_args] / #[syscall_handler], etc. etc.  The trampoline implementations (specifically when writing the #[syscall_handler]
macro) were the thing that broke the previous way of doing this, because there's no way to propagate the types used to construct the Syscall ISR through
the SyscallInvocation / Trampoline / SyscallHandler chain.

What would be even nicer is that if the Syscalls could be registered in a manner similar to the ISR vector table, so that we continually chain calls to
some 'const fn' to build up a table that exposes a (SyscallInvocationFactory, SyscallHandler) pair, but I don't think that's possible to do through 'const'...
It would get rid of the magic linker section and taking the address of 'known' statics though, but the Board driver would become messy (perhaps ?)
*/

#[syscall_args]
pub struct BlinkyBlinkySyscall {
    blink: usize
}

pub struct BlinkyBlinkySyscallHandler<D: Dependencies> {
    _dependencies: PhantomData<D>
}
// able to inject a bunch of dependencies for the macro to 'impl IsrTrampoline for BlinkyBlinky<A, B, C, ...>' with the well-defined static (ie. compilable
// because we know the type and aren't using an unknown 'hoisted' generic).

impl<D: Dependencies> SyscallIsrHandler for BlinkyBlinkySyscallHandler<D> {
    type IsrContext = D::IsrContext;
    type Args = BlinkyBlinkySyscall;

    fn on_syscall(context: &mut SyscallIsrContext<Self::IsrContext, Self::Args>) -> SyscallResult {
        unsafe {
//            let blink = context.args_mut().assume_init().blink;
static mut blink: usize = 0;

            // Port output register
            let gpiob_odr = &raw mut __LINKER_PERIPHERALS_AHB2_GPIOB.ODR;
            let mut odr = core::ptr::read_volatile(gpiob_odr);
            if blink != 0 {
                odr |= 1 << 3;
            } else {
                odr &= !(1 << 3);
            }
blink ^= 1;
            core::ptr::write_volatile(gpiob_odr, odr);
            Ok(())
        }
    }
}






/*
TODO: was in the middle of refining this but have to stop...but basically we can build up a list of syscall registrations in a 'const' context.
Then we ought to be able to register each syscall with its ID based on the position in that tuple.  Perhaps.  It should also allow the injection
of _something from_ Syscall::Dependencies for the SyscallInvocation and SyscallContext of the handlers.  Then each driver can request a Syscall Driver
as a dependency that can be called to register / build up its list of syscalls, much like the list of ISRs that are collected (that is co-ordinated
by the Board).


trait SyscallRegistration {
    type Args;
    type Handler;
}

struct SyscallArgsA;
struct SyscallArgsB;
struct SyscallArgsC;

struct SyscallHandlerA;
struct SyscallHandlerB;
struct SyscallHandlerC;

struct SyscallContainer<A, H> {
    _a: std::marker::PhantomData<A>,
    _h: std::marker::PhantomData<H>
}

impl<A, H> SyscallRegistration for SyscallContainer<A, H> {
    type Args = A;
    type Handler = H;
}

#[derive(Debug)]
struct SyscallDriver<T> {
    syscalls: T
}

impl<T> SyscallDriver<T> where T: SyscallRegistration {
    pub const fn new<U: SyscallRegistration>(first: U) -> SyscallDriver<(U)> {
        SyscallDriver { syscalls: (U) }
    }

    pub const fn add<U: SyscallRegistration>(self, other: U) -> SyscallDriver<(T, U)> {
        SyscallDriver::<(T, U)> { syscalls: (self.syscalls, other) }
    }
}

type FnPtr = fn(u32) -> u16;

fn something(x: u32) -> u16 { x as u16 }

fn main() {
    let driver = SyscallDriver::<()>::new().add(123).add(4.56).add(789);//.add(something);
    println!("Syscalls: {:?}", driver);
}

---------------------------------------------

use std::marker::PhantomData;

type Cons0 = ();
type Cons1<T> = (T, Cons0);
type Cons2<T1, T2> = (T1, Cons1<T2>);
type Cons3<T1, T2, T3> = (T1, Cons2<T2, T3>);
type Cons4<T1, T2, T3, T4> = (T1, Cons3<T2, T3, T4>);

trait Driver { }

trait SyscallHandler { }

#[derive(Debug)]
struct SyscallRegistration<H: SyscallHandler> {
    _handler: PhantomData<H>
}

type SyscallRegistrations0 = Cons0;
type SyscallRegistrations1<H: SyscallHandler> = Cons1<SyscallRegistration<H>>;
type SyscallRegistrations2<H1: SyscallHandler, H2: SyscallHandler> = Cons2<SyscallRegistration<H1>, SyscallRegistration<H2>>;
type SyscallRegistrations3<H1: SyscallHandler, H2: SyscallHandler, H3: SyscallHandler> = Cons3<SyscallRegistration<H1>, SyscallRegistration<H2>, SyscallRegistration<H3>>;

#[derive(Debug)]
struct SyscallHandlerA;
impl SyscallHandler for SyscallHandlerA { }

#[derive(Debug)]
struct SyscallHandlerB;
impl SyscallHandler for SyscallHandlerB { }

#[derive(Debug)]
struct SyscallHandlerC;
impl SyscallHandler for SyscallHandlerC { }

#[derive(Debug)]
struct DriverA;
impl Driver for DriverA { }
impl DriverA {
    const fn syscall_handlers() -> SyscallRegistrations2<SyscallHandlerA, SyscallHandlerB> {
        (SyscallRegistration { _handler: PhantomData }, (SyscallRegistration { _handler: PhantomData }, ()))
    }
}

#[derive(Debug)]
struct DriverB;
impl Driver for DriverB { }
impl DriverB {
    const fn syscall_handlers() -> SyscallRegistrations0 {
    }
}

#[derive(Debug)]
struct DriverC;
impl Driver for DriverC { }
impl DriverC {
    const fn syscall_handlers() -> SyscallRegistrations1<SyscallHandlerC> {
        (SyscallRegistration { _handler: PhantomData }, ())
    }
}

fn main() {
    const DRIVERS: Cons3<DriverA, DriverB, DriverC> = push_front(push_front((DriverC, ()), DriverB), DriverA); // (DriverA, Cons2(DriverB, Cons1(DriverC, Cons0)));
    const SYSCALL_HANDLERS: [u32; 3/* _ doesn't work - we need to count the number of Cons entries ! How to iterate ??? */] = [1, 2, 3]; // TODO: can we reduce the syscalls from the drivers to an array of function pointers ?  Playing with u32 for simplicity here...

    println!("DRIVERS = {DRIVERS:?}");
}

const fn push_front<H, T>(items: T, head: H) -> (H, T) {
    (head, items)
}


-----------------------------------


use std::ops::Add;

#[derive(Debug)]
enum ConsCell<'a, T> {
    None,
    Some(T, &'a ConsCell<'a, T>),
}

fn main() {
    const X: ConsCell<'_, isize> = ConsCell::Some(1, &ConsCell::Some(2, &ConsCell::Some(3, &ConsCell::None)));
    const SUM_X: isize = cons_sum(&X);

    println!("x = {X:?}");
    println!("sum(x) = {}", SUM_X);
}

const fn cons_sum(list: &ConsCell<'_, isize>) -> isize {
    match *list {
        ConsCell::None => 0,
        ConsCell::Some(val, list) => val + cons_sum(list)
    }
}

*/
