[package]
name = "smeg-mcu-st-stm32_family"
version = "0.1.0"
edition = "2024"
authors = ["Pete Restall <pete@restall.net>"]

[dependencies]
smeg-kernel = { path = "../../../kernel" }

[features]
std = ["smeg-kernel/std"]
