[package]
name = "smeg-kernel"
version = "0.1.0"
edition = "2024"
authors = ["Pete Restall <pete@restall.net>"]

[dependencies]
smeg-config = { path = "../config" }
smeg-kernel-procmacro = { path = "procmacro" }
