[package]
name = "smeg-os"
version = "0.1.0"
edition = "2024"
authors = ["Pete Restall <pete@restall.net>"]

[dependencies]
smeg-board-st-nucleo_l432kc = { path = "../boards/st/nucleo_l432kc", optional = true}
smeg-kernel = { path = "../kernel" }

[features]
smeg-board-st-nucleo_l432kc-default = ["dep:smeg-board-st-nucleo_l432kc"]
