[package]
name = "smeg-mcu-host-rust_std"
version = "0.1.0"
edition = "2024"
authors = ["Pete Restall <pete@restall.net>"]

[dependencies]
smeg-config = { path = "../../../config" }
smeg-kernel = { path = "../../../kernel" }

[features]
default = ["std"]
std = ["smeg-kernel/std"]
