use smeg_kernel::docs;

#[macro_export]
#[doc = docs::side_by_side_md!("isr_fn_trampolines")]
macro_rules! isr_fn_trampolines {
    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "handler_main"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, mut, mut, IsrBasicStackFrame, $target_fn_name, 0xf1_u8 ) } /* TODO: 0xe1_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "thread_main"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, mut, mut, IsrBasicStackFrame, $target_fn_name, 0xf9_u8 ) } /* TODO: 0xe9_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "thread_process"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, mut, mut, IsrBasicStackFrame, $target_fn_name, 0xfd_u8 ) } /* TODO: 0xed_u8 when using FP with extended frame... */
    };

    ( @__(
        $doc_attr:ident,
        $trampoline_fn_name:ident,
        $ptr_mutability:ident,
        $ref_mutability:ident,
        $frame_type:ident,
        $target_fn_name:ident,
        $fn_return:literal ) ) => {

        #[cfg_attr(target_arch = "arm", naked)]
        #[doc = isr_fn_trampolines! { @__( $doc_attr ) }]
        unsafe extern "C" fn $trampoline_fn_name() -> ! {
            ::cfg_if::cfg_if! {
                if #[cfg(target_arch = "arm")] {
                    unsafe extern "C" fn trampoline(frame: *$ptr_mutability ::smeg_mcu_arm_cortex_m4_family::interrupts::$frame_type) {
                        unsafe {
                            $target_fn_name(&$ref_mutability *frame)
                        }
                    }

                    ::core::arch::naked_asm!(r#"
                        mov r0, sp
                        mvn lr, #{isr_retval}
                        b {trampoline}"#,
                        isr_retval = const !$fn_return,
                        trampoline = sym trampoline);

                } else {
                    panic!("Cannot call a Cortex M4 ISR trampoline on a non-Cortex M4 (running tests ?)");
                }
            }
        }
    };

    ( @__( doc_attr ) ) => {
        r#"
            Interrupt Service Routine (ISR) with access to a Basic Stack Frame as per Section B1.5.7 of the ARMv7-M Architecture Reference Manual.

            Trampoline stub generated by `smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { ... }`.
        "#
    };

    ( @__( doc_attr_mut ) ) => {
        r#"
            Interrupt Service Routine (ISR) with *mutable* access to a Basic Stack Frame as per Section B1.5.7 of the ARMv7-M Architecture Reference Manual.

            Trampoline stub generated by `smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { ... }`.

            _The use-cases for this function signature are very limited - did you perhaps mean to use the *immutable* signature, instead ?_

            Highly unsafe !  Any modification to the pushed registers will result in _Undefined Behaviour_ according to the rules of
            [Inline Assembly](https://doc.rust-lang.org/reference/inline-assembly.html#r-asm.rules.reg-not-output) !

            An example use-case of when mutating the stacked registers does not result in _Undefined Behaviour_ is that of Syscalls.  In this
            scenario, the `SV_CALL` interrupt is invoked synchronously with the control of the application via an assembly-language stub so any
            mutations are able to be codified as `out` arguments and not interfere with Rust's assumptions and optimisations.  Any ISR that can
            be _invoked asynchronously_ to program flow should _not use this ISR_ !
        "#
    };
}

pub mod prelude {
}
