#[repr(C)]
pub struct IsrBasicStackFrame {
    pub r0: usize,
    pub r1: usize,
    pub r2: usize,
    pub r3: usize,
    pub r12: usize,
    pub r14_lr: usize,
    pub return_address: usize,
    pub xpsr: usize
}

const _: () = {
    assert!(size_of::<IsrBasicStackFrame>() == 8 * size_of::<usize>(), "Size of IsrBasicStackFrame must be exactly 8 machine words");
    assert!(align_of::<IsrBasicStackFrame>() == align_of::<usize>(), "Alignment of IsrBasicStackFrame must be the same as a machine word");
};

pub type IsrFnMut<T> = unsafe extern "C" fn(&mut T);

#[macro_export]
macro_rules! isr_fn_trampolines {
    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "handler_main"; ) => {
        isr_fn_trampolines! { @__( $trampoline_fn_name, mut, IsrBasicStackFrame, $target_fn_name, 0xf1_u8 ) } /* TODO: 0xe1_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "thread_main"; ) => {
        isr_fn_trampolines! { @__( $trampoline_fn_name, mut, IsrBasicStackFrame, $target_fn_name, 0xf9_u8 ) } /* TODO: 0xe9_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident(&mut IsrBasicStackFrame) -> $target_fn_name:ident -> "thread_process"; ) => {
        isr_fn_trampolines! { @__( $trampoline_fn_name, mut, IsrBasicStackFrame, $target_fn_name, 0xfd_u8 ) } /* TODO: 0xed_u8 when using FP with extended frame... */
    };

    ( @__( $trampoline_fn_name:ident, $mutability:ident, $frame_type:ident, $target_fn_name:ident, $fn_return:literal ) ) => {
        #[naked]
        unsafe extern "C" fn $trampoline_fn_name() -> ! {
//            const _: ::smeg_mcu_arm_cortex_m4_family::interrupts::IsrFnMut<::smeg_mcu_arm_cortex_m4_family::interrupts::IsrBasicStackFrame> = #fn_name;

            unsafe extern "C" fn trampoline(frame: *$mutability $frame_type /*frame_addr: usize*/) {/*
                let mut frame = (); // TODO: an attempt at creating provenance given a usize, but this might be UB because it's the stack which isn't disjoint to Rust's working memory... HOWEVER...doesn't work, whereas a raw pointer from asm!(...) does... :-/
                let mut frame = &$mutability frame as *$mutability ();
                let mut frame = frame.with_addr(frame_addr).cast::<$frame_type>();*/
                unsafe {
                    $target_fn_name(&$mutability *frame);
                }
            }

            ::core::arch::naked_asm!(r#"
                mov r0, sp
                mvn lr, #{isr_retval}
                b {trampoline}"#,
                isr_retval = const !$fn_return,
                trampoline = sym trampoline);
        }
    };
}

/*
macro_rules! isr_fn_context {
    (
        $(fn_attrs:meta)*
        unsafe extern "C" fn $fn_name:ident($frame_arg:ident: &mut IsrBasicStackFrame) {
            $fn_body:tt
        }
    ) => {
        #[doc = r#"
            Interrupt Service Routine (ISR) with *mutable* access to a Basic Stack Frame as per `B1.5.7` in the ARMv7-M Architecture Reference Manual.

            Stub generated by `smeg_mcu_arm_cortex_m4_family::isr_fn_context! { ... }`.

            _The use-cases for this function signature are very limited - did you perhaps mean to use the *immutable* signature, instead ?_

            Highly unsafe !  Any modification to the pushed registers will result in _Undefined Behaviour_ according to the rules of
            [Inline Assembly](https://doc.rust-lang.org/reference/inline-assembly.html#r-asm.rules.reg-not-output) !

            An example use-case of when mutating the stacked registers does not result in _Undefined Behaviour_ is that of Syscalls.  In this
            scenario, the `SV_CALL` interrupt is invoked synchronously with the control of the application via an assembly-language stub so any
            mutations are able to be codified as `out` arguments and not interfere with Rust's assumptions and optimisations.  Any ISR that can
            be _invoked asynchronously_ to program flow should _not use this ISR_ !
        "#]
        #[unsafe(naked)]
        unsafe extern "C" fn #fn_name() -> ! {
            #(#fn_attrs)*
            unsafe extern "C" fn isr(#frame_arg: &mut IsrBasicStackFrame) {
                #fn_body
            }

            ::core::arch::naked_asm!(r#"
            "#,
            sym isr);

            // TODO: how to return ?!?
        }
    };
}
*/

pub mod prelude {
    pub use super::{IsrBasicStackFrame, IsrFnMut};
}
