use smeg_kernel::docs;

// TODO: documentation needs updating...
#[macro_export]
#[doc = docs::side_by_side_md!("isr_fn_trampolines")]
macro_rules! isr_fn_trampolines {
    ( fn $trampoline_fn_name:ident() -> $target_fn_name:ident<$($context_traits:ty),*>() -> "handler_main"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, $target_fn_name, ($($context_traits),*), 0xf1_u8 ) } /* TODO: 0xe1_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident() -> $target_fn_name:ident<$($context_traits:ty),*>() -> "thread_main"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, $target_fn_name, ($($context_traits),*), 0xf9_u8 ) } /* TODO: 0xe9_u8 when using FP with extended frame... */
    };

    ( fn $trampoline_fn_name:ident() -> $target_fn_name:ident<$($context_traits:ty),*>() -> "thread_process"; ) => {
        ::smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { @__( doc_attr_mut, $trampoline_fn_name, $target_fn_name, ($($context_traits),*), 0xfd_u8 ) } /* TODO: 0xed_u8 when using FP with extended frame... */
    };

    ( @__(
        $doc_attr:ident,
        $trampoline_fn_name:ident,
        $target_fn_name:ident,
        ($($context_traits:ty),*),
        $fn_return:literal ) ) => {

        #[cfg_attr(target_arch = "arm", naked)]
        #[doc = isr_fn_trampolines! { @__( $doc_attr ) }] // TODO: doc can now be common for all trampolines
        unsafe extern "C" fn $trampoline_fn_name<C>() -> !
            where C:
                ::smeg_kernel::interrupts::IsrContext +
                ::core::convert::From<::smeg_mcu_arm_cortex_m4_family::interrupts::IsrContextImpl> +
                ::core::borrow::BorrowMut<::smeg_mcu_arm_cortex_m4_family::interrupts::IsrContextImpl>
                $(+ $context_traits)* {

            ::cfg_if::cfg_if! {
                if #[cfg(target_arch = "arm")] {
                    unsafe extern "C" fn trampoline<C>(stack_frame: *mut ::smeg_mcu_arm_cortex_m4_family::interrupts::IsrBasicStackFrame)
                        where C:
                            ::smeg_kernel::interrupts::IsrContext +
                            ::core::convert::From<::smeg_mcu_arm_cortex_m4_family::interrupts::IsrContextImpl> +
                            ::core::borrow::BorrowMut<::smeg_mcu_arm_cortex_m4_family::interrupts::IsrContextImpl>
                            $(+ $context_traits)* {

                        let mut context = C::from(::smeg_mcu_arm_cortex_m4_family::interrupts::IsrContextImpl::from(stack_frame));
                        unsafe {
                            $target_fn_name(&mut context)
                        }
                    }

                    ::core::arch::naked_asm!(r#"
                        mov r0, sp
                        mvn lr, #{isr_retval}
                        b {trampoline}"#,
                        isr_retval = const !$fn_return,
                        trampoline = sym trampoline::<C>);

                } else {
                    panic!("Cannot call a Cortex M4 ISR trampoline on a non-Cortex M4 (running tests ?)");
                }
            }
        }
    };

    ( @__( doc_attr ) ) => {
        r#"
            Interrupt Service Routine (ISR) with access to a Basic Stack Frame as per Section B1.5.7 of the ARMv7-M Architecture Reference Manual.

            Trampoline stub generated by `smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { ... }`.
        "#
    };

    ( @__( doc_attr_mut ) ) => {
        r#"
            Interrupt Service Routine (ISR) with *mutable* access to a Basic Stack Frame as per Section B1.5.7 of the ARMv7-M Architecture Reference Manual.

            Trampoline stub generated by `smeg_mcu_arm_cortex_m4_family::isr_fn_trampolines! { ... }`.

            _The use-cases for this function signature are very limited - did you perhaps mean to use the *immutable* signature, instead ?_

            Highly unsafe !  Any modification to the pushed registers will result in _Undefined Behaviour_ according to the rules of
            [Inline Assembly](https://doc.rust-lang.org/reference/inline-assembly.html#r-asm.rules.reg-not-output) !

            An example use-case of when mutating the stacked registers does not result in _Undefined Behaviour_ is that of Syscalls.  In this
            scenario, the `SV_CALL` interrupt is invoked synchronously with the control of the application via an assembly-language stub so any
            mutations are able to be codified as `out` arguments and not interfere with Rust's assumptions and optimisations.  Any ISR that can
            be _invoked asynchronously_ to program flow should _not use this ISR_ !
        "#
    };
}

pub mod prelude {
}
