use smeg_kernel::const_unwrap_or;

use smeg_mcu_arm_cortex_m4_family::interrupts::{
    IsrVector,
    IsrVectorTable as CortexM4IsrVectorTable,
    IsrVectorTableBuilder as CortexM4IsrVectorTableBuilder,
    RESERVED_ISR_VECTOR,
    UNHANDLED_ISR_VECTOR
};

// TODO: Is this boilerplate a candidate for something like #[derive(IsrVectorTableBuilder)] ?
pub struct IsrVectorTableBuilder {
    pub cortex_m4: CortexM4IsrVectorTableBuilder,
    pub wwdg: Option<IsrVector>,
    pub pvd_pvm: Option<IsrVector>,
    pub rtc_tamp_css_lse: Option<IsrVector>,
    pub rtc_wkup: Option<IsrVector>,
    pub flash: Option<IsrVector>,
    pub rcc: Option<IsrVector>,
    pub exti0: Option<IsrVector>,
    pub exti1: Option<IsrVector>,
    pub exti2: Option<IsrVector>,
    pub exti3: Option<IsrVector>,
    pub exti4: Option<IsrVector>,
    pub dma1_ch1: Option<IsrVector>,
    pub dma1_ch2: Option<IsrVector>,
    pub dma1_ch3: Option<IsrVector>,
    pub dma1_ch4: Option<IsrVector>,
    pub dma1_ch5: Option<IsrVector>,
    pub dma1_ch6: Option<IsrVector>,
    pub dma1_ch7: Option<IsrVector>,
    pub adc1: Option<IsrVector>,
    pub can1_tx: Option<IsrVector>,
    pub can1_rx0: Option<IsrVector>,
    pub can1_rx1: Option<IsrVector>,
    pub can1_sce: Option<IsrVector>,
    pub exti9_5: Option<IsrVector>,
    pub tim1_brk_tim15: Option<IsrVector>,
    pub tim1_up_tim16: Option<IsrVector>,
    pub tim1_trg_com: Option<IsrVector>,
    pub tim1_cc: Option<IsrVector>,
    pub tim2: Option<IsrVector>,
    pub i2c1_ev: Option<IsrVector>,
    pub i2c1_er: Option<IsrVector>,
    pub spi1: Option<IsrVector>,
    pub usart1: Option<IsrVector>,
    pub usart2: Option<IsrVector>,
    pub exti15_10: Option<IsrVector>,
    pub rtc_alarm: Option<IsrVector>,
    pub spi3: Option<IsrVector>,
    pub tim6_dac_under: Option<IsrVector>,
    pub tim7: Option<IsrVector>,
    pub dma2_ch1: Option<IsrVector>,
    pub dma2_ch2: Option<IsrVector>,
    pub dma2_ch3: Option<IsrVector>,
    pub dma2_ch4: Option<IsrVector>,
    pub dma2_ch5: Option<IsrVector>,
    pub comp: Option<IsrVector>,
    pub lp_tim1: Option<IsrVector>,
    pub lp_tim2: Option<IsrVector>,
    pub usb_fs: Option<IsrVector>,
    pub dma2_ch6: Option<IsrVector>,
    pub dma2_ch7: Option<IsrVector>,
    pub lp_uart1: Option<IsrVector>,
    pub quad_spi: Option<IsrVector>,
    pub i2c3_ev: Option<IsrVector>,
    pub i2c3_er: Option<IsrVector>,
    pub sai1: Option<IsrVector>,
    pub swpmi1: Option<IsrVector>,
    pub tsc: Option<IsrVector>,
    pub aes: Option<IsrVector>,
    pub rng: Option<IsrVector>,
    pub fpu: Option<IsrVector>,
    pub crs: Option<IsrVector>
}

impl IsrVectorTableBuilder {
    pub const fn default() -> Self {
        Self {
            cortex_m4: CortexM4IsrVectorTableBuilder::default(),
            wwdg: None,
            pvd_pvm: None,
            rtc_tamp_css_lse: None,
            rtc_wkup: None,
            flash: None,
            rcc: None,
            exti0: None,
            exti1: None,
            exti2: None,
            exti3: None,
            exti4: None,
            dma1_ch1: None,
            dma1_ch2: None,
            dma1_ch3: None,
            dma1_ch4: None,
            dma1_ch5: None,
            dma1_ch6: None,
            dma1_ch7: None,
            adc1: None,
            can1_tx: None,
            can1_rx0: None,
            can1_rx1: None,
            can1_sce: None,
            exti9_5: None,
            tim1_brk_tim15: None,
            tim1_up_tim16: None,
            tim1_trg_com: None,
            tim1_cc: None,
            tim2: None,
            i2c1_ev: None,
            i2c1_er: None,
            spi1: None,
            usart1: None,
            usart2: None,
            exti15_10: None,
            rtc_alarm: None,
            spi3: None,
            tim6_dac_under: None,
            tim7: None,
            dma2_ch1: None,
            dma2_ch2: None,
            dma2_ch3: None,
            dma2_ch4: None,
            dma2_ch5: None,
            comp: None,
            lp_tim1: None,
            lp_tim2: None,
            usb_fs: None,
            dma2_ch6: None,
            dma2_ch7: None,
            lp_uart1: None,
            quad_spi: None,
            i2c3_ev: None,
            i2c3_er: None,
            sai1: None,
            swpmi1: None,
            tsc: None,
            aes: None,
            rng: None,
            fpu: None,
            crs: None
        }
    }
}

#[repr(C)]
pub struct IsrVectorTable {
    pub cortex_m4: CortexM4IsrVectorTable,
    pub wwdg: IsrVector,
    pub pvd_pvm: IsrVector,
    pub rtc_tamp_css_lse: IsrVector,
    pub rtc_wkup: IsrVector,
    pub flash: IsrVector,
    pub rcc: IsrVector,
    pub exti0: IsrVector,
    pub exti1: IsrVector,
    pub exti2: IsrVector,
    pub exti3: IsrVector,
    pub exti4: IsrVector,
    pub dma1_ch1: IsrVector,
    pub dma1_ch2: IsrVector,
    pub dma1_ch3: IsrVector,
    pub dma1_ch4: IsrVector,
    pub dma1_ch5: IsrVector,
    pub dma1_ch6: IsrVector,
    pub dma1_ch7: IsrVector,
    pub adc1: IsrVector,
    pub can1_tx: IsrVector,
    pub can1_rx0: IsrVector,
    pub can1_rx1: IsrVector,
    pub can1_sce: IsrVector,
    pub exti9_5: IsrVector,
    pub tim1_brk_tim15: IsrVector,
    pub tim1_up_tim16: IsrVector,
    pub tim1_trg_com: IsrVector,
    pub tim1_cc: IsrVector,
    pub tim2: IsrVector,
    _unavailable_tim3: IsrVector,
    _reserved_46: IsrVector,
    pub i2c1_ev: IsrVector,
    pub i2c1_er: IsrVector,
    _unavailable_i2c2_ev: IsrVector,
    _unavailable_i2c2_er: IsrVector,
    pub spi1: IsrVector,
    _unavailable_spi2: IsrVector,
    pub usart1: IsrVector,
    pub usart2: IsrVector,
    _unavailable_usart3: IsrVector,
    pub exti15_10: IsrVector,
    pub rtc_alarm: IsrVector,
    _reserved_58: IsrVector,
    _reserved_59: IsrVector,
    _reserved_60: IsrVector,
    _reserved_61: IsrVector,
    _reserved_62: IsrVector,
    _reserved_63: IsrVector,
    _reserved_64: IsrVector,
    _unavailable_sdmmc1: IsrVector,
    _reserved_66: IsrVector,
    pub spi3: IsrVector,
    _unavailable_uart4: IsrVector,
    _reserved_69: IsrVector,
    pub tim6_dac_under: IsrVector,
    pub tim7: IsrVector,
    pub dma2_ch1: IsrVector,
    pub dma2_ch2: IsrVector,
    pub dma2_ch3: IsrVector,
    pub dma2_ch4: IsrVector,
    pub dma2_ch5: IsrVector,
    _unavailable_dfsdm1_flt0: IsrVector,
    _unavailable_dfsdm1_flt1: IsrVector,
    _reserved_79: IsrVector,
    pub comp: IsrVector,
    pub lp_tim1: IsrVector,
    pub lp_tim2: IsrVector,
    pub usb_fs: IsrVector,
    pub dma2_ch6: IsrVector,
    pub dma2_ch7: IsrVector,
    pub lp_uart1: IsrVector,
    pub quad_spi: IsrVector,
    pub i2c3_ev: IsrVector,
    pub i2c3_er: IsrVector,
    pub sai1: IsrVector,
    _reserved_91: IsrVector,
    pub swpmi1: IsrVector,
    pub tsc: IsrVector,
    _unavailable_lcd: IsrVector,
    pub aes: IsrVector,
    pub rng: IsrVector,
    pub fpu: IsrVector,
    pub crs: IsrVector,
    _unavailable_i2c4_ev: IsrVector,
    _reserved_100: IsrVector
}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(
        size_of::<IsrVectorTable>() == (85 * 4) + size_of::<CortexM4IsrVectorTable>(),
        "There must be 85 ISR vectors for the STM32L432KC, each 32-bits");

    assert!(align_of::<IsrVectorTable>() == 4, "Alignment of the ISR vector table must be 32-bits");
};

impl IsrVectorTable {
    pub const fn from(isrs: IsrVectorTableBuilder) -> Self {
        Self {
            cortex_m4: CortexM4IsrVectorTable::from(isrs.cortex_m4),
            wwdg: const_unwrap_or(isrs.wwdg, UNHANDLED_ISR_VECTOR),
            pvd_pvm: const_unwrap_or(isrs.pvd_pvm, UNHANDLED_ISR_VECTOR),
            rtc_tamp_css_lse: const_unwrap_or(isrs.rtc_tamp_css_lse, UNHANDLED_ISR_VECTOR),
            rtc_wkup: const_unwrap_or(isrs.rtc_wkup, UNHANDLED_ISR_VECTOR),
            flash: const_unwrap_or(isrs.flash, UNHANDLED_ISR_VECTOR),
            rcc: const_unwrap_or(isrs.rcc, UNHANDLED_ISR_VECTOR),
            exti0: const_unwrap_or(isrs.exti0, UNHANDLED_ISR_VECTOR),
            exti1: const_unwrap_or(isrs.exti1, UNHANDLED_ISR_VECTOR),
            exti2: const_unwrap_or(isrs.exti2, UNHANDLED_ISR_VECTOR),
            exti3: const_unwrap_or(isrs.exti3, UNHANDLED_ISR_VECTOR),
            exti4: const_unwrap_or(isrs.exti4, UNHANDLED_ISR_VECTOR),
            dma1_ch1: const_unwrap_or(isrs.dma1_ch1, UNHANDLED_ISR_VECTOR),
            dma1_ch2: const_unwrap_or(isrs.dma1_ch2, UNHANDLED_ISR_VECTOR),
            dma1_ch3: const_unwrap_or(isrs.dma1_ch3, UNHANDLED_ISR_VECTOR),
            dma1_ch4: const_unwrap_or(isrs.dma1_ch4, UNHANDLED_ISR_VECTOR),
            dma1_ch5: const_unwrap_or(isrs.dma1_ch5, UNHANDLED_ISR_VECTOR),
            dma1_ch6: const_unwrap_or(isrs.dma1_ch6, UNHANDLED_ISR_VECTOR),
            dma1_ch7: const_unwrap_or(isrs.dma1_ch7, UNHANDLED_ISR_VECTOR),
            adc1: const_unwrap_or(isrs.adc1, UNHANDLED_ISR_VECTOR),
            can1_tx: const_unwrap_or(isrs.can1_tx, UNHANDLED_ISR_VECTOR),
            can1_rx0: const_unwrap_or(isrs.can1_rx0, UNHANDLED_ISR_VECTOR),
            can1_rx1: const_unwrap_or(isrs.can1_rx1, UNHANDLED_ISR_VECTOR),
            can1_sce: const_unwrap_or(isrs.can1_sce, UNHANDLED_ISR_VECTOR),
            exti9_5: const_unwrap_or(isrs.exti9_5, UNHANDLED_ISR_VECTOR),
            tim1_brk_tim15: const_unwrap_or(isrs.tim1_brk_tim15, UNHANDLED_ISR_VECTOR),
            tim1_up_tim16: const_unwrap_or(isrs.tim1_up_tim16, UNHANDLED_ISR_VECTOR),
            tim1_trg_com: const_unwrap_or(isrs.tim1_trg_com, UNHANDLED_ISR_VECTOR),
            tim1_cc: const_unwrap_or(isrs.tim1_cc, UNHANDLED_ISR_VECTOR),
            tim2: const_unwrap_or(isrs.tim2, UNHANDLED_ISR_VECTOR),
            i2c1_ev: const_unwrap_or(isrs.i2c1_ev, UNHANDLED_ISR_VECTOR),
            i2c1_er: const_unwrap_or(isrs.i2c1_er, UNHANDLED_ISR_VECTOR),
            spi1: const_unwrap_or(isrs.spi1, UNHANDLED_ISR_VECTOR),
            usart1: const_unwrap_or(isrs.usart1, UNHANDLED_ISR_VECTOR),
            usart2: const_unwrap_or(isrs.usart2, UNHANDLED_ISR_VECTOR),
            exti15_10: const_unwrap_or(isrs.exti15_10, UNHANDLED_ISR_VECTOR),
            rtc_alarm: const_unwrap_or(isrs.rtc_alarm, UNHANDLED_ISR_VECTOR),
            spi3: const_unwrap_or(isrs.spi3, UNHANDLED_ISR_VECTOR),
            tim6_dac_under: const_unwrap_or(isrs.tim6_dac_under, UNHANDLED_ISR_VECTOR),
            tim7: const_unwrap_or(isrs.tim7, UNHANDLED_ISR_VECTOR),
            dma2_ch1: const_unwrap_or(isrs.dma2_ch1, UNHANDLED_ISR_VECTOR),
            dma2_ch2: const_unwrap_or(isrs.dma2_ch2, UNHANDLED_ISR_VECTOR),
            dma2_ch3: const_unwrap_or(isrs.dma2_ch3, UNHANDLED_ISR_VECTOR),
            dma2_ch4: const_unwrap_or(isrs.dma2_ch4, UNHANDLED_ISR_VECTOR),
            dma2_ch5: const_unwrap_or(isrs.dma2_ch5, UNHANDLED_ISR_VECTOR),
            comp: const_unwrap_or(isrs.comp, UNHANDLED_ISR_VECTOR),
            lp_tim1: const_unwrap_or(isrs.lp_tim1, UNHANDLED_ISR_VECTOR),
            lp_tim2: const_unwrap_or(isrs.lp_tim2, UNHANDLED_ISR_VECTOR),
            usb_fs: const_unwrap_or(isrs.usb_fs, UNHANDLED_ISR_VECTOR),
            dma2_ch6: const_unwrap_or(isrs.dma2_ch6, UNHANDLED_ISR_VECTOR),
            dma2_ch7: const_unwrap_or(isrs.dma2_ch7, UNHANDLED_ISR_VECTOR),
            lp_uart1: const_unwrap_or(isrs.lp_uart1, UNHANDLED_ISR_VECTOR),
            quad_spi: const_unwrap_or(isrs.quad_spi, UNHANDLED_ISR_VECTOR),
            i2c3_ev: const_unwrap_or(isrs.i2c3_ev, UNHANDLED_ISR_VECTOR),
            i2c3_er: const_unwrap_or(isrs.i2c3_er, UNHANDLED_ISR_VECTOR),
            sai1: const_unwrap_or(isrs.sai1, UNHANDLED_ISR_VECTOR),
            swpmi1: const_unwrap_or(isrs.swpmi1, UNHANDLED_ISR_VECTOR),
            tsc: const_unwrap_or(isrs.tsc, UNHANDLED_ISR_VECTOR),
            aes: const_unwrap_or(isrs.aes, UNHANDLED_ISR_VECTOR),
            rng: const_unwrap_or(isrs.rng, UNHANDLED_ISR_VECTOR),
            fpu: const_unwrap_or(isrs.fpu, UNHANDLED_ISR_VECTOR),
            crs: const_unwrap_or(isrs.crs, UNHANDLED_ISR_VECTOR),

            _unavailable_tim3: RESERVED_ISR_VECTOR,
            _reserved_46: RESERVED_ISR_VECTOR,
            _unavailable_i2c2_ev: RESERVED_ISR_VECTOR,
            _unavailable_i2c2_er: RESERVED_ISR_VECTOR,
            _unavailable_spi2: RESERVED_ISR_VECTOR,
            _unavailable_usart3: RESERVED_ISR_VECTOR,
            _reserved_58: RESERVED_ISR_VECTOR,
            _reserved_59: RESERVED_ISR_VECTOR,
            _reserved_60: RESERVED_ISR_VECTOR,
            _reserved_61: RESERVED_ISR_VECTOR,
            _reserved_62: RESERVED_ISR_VECTOR,
            _reserved_63: RESERVED_ISR_VECTOR,
            _reserved_64: RESERVED_ISR_VECTOR,
            _unavailable_sdmmc1: RESERVED_ISR_VECTOR,
            _reserved_66: RESERVED_ISR_VECTOR,
            _unavailable_uart4: RESERVED_ISR_VECTOR,
            _reserved_69: RESERVED_ISR_VECTOR,
            _unavailable_dfsdm1_flt0: RESERVED_ISR_VECTOR,
            _unavailable_dfsdm1_flt1: RESERVED_ISR_VECTOR,
            _reserved_79: RESERVED_ISR_VECTOR,
            _reserved_91: RESERVED_ISR_VECTOR,
            _unavailable_lcd: RESERVED_ISR_VECTOR,
            _unavailable_i2c4_ev: RESERVED_ISR_VECTOR,
            _reserved_100: RESERVED_ISR_VECTOR
        }
    }
}

#[macro_export]
macro_rules! define_isr_vector_table_from {
    ($isrs:expr) => {
        #[used]
        #[unsafe(link_section = ".smeg.isr_vector_table.st.stm32l432kc")]
        static _ISR_VECTOR_TABLE: $crate::interrupts::IsrVectorTable = $crate::interrupts::IsrVectorTable::from($isrs);
    }
}
