[workspace]
members = [
	"crates/boards/*/*",
	"crates/drivers/*",
	"crates/kernel",
	"crates/drivers/*",
	"crates/mcus/*/*",
	"crates/os"]

default-members = ["crates/os"]

resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
debug = true
panic = "abort"
