use smeg_mcu_arm_cortex_m4_family::interrupts::{
    IsrVector,
    IsrVectorTable as CortexM4IsrVectorTable,
    RESERVED_ISR_VECTOR,
    with_default_unhandled
};

#[repr(C)]
pub struct IsrVectorTable {
    pub cortex_m4: CortexM4IsrVectorTable,
    pub wwdg: Option<IsrVector>,
    pub pvd_pvm: Option<IsrVector>,
    pub rtc_tamp_css_lse: Option<IsrVector>,
    pub rtc_wkup: Option<IsrVector>,
    pub flash: Option<IsrVector>,
    pub rcc: Option<IsrVector>,
    pub exti0: Option<IsrVector>,
    pub exti1: Option<IsrVector>,
    pub exti2: Option<IsrVector>,
    pub exti3: Option<IsrVector>,
    pub exti4: Option<IsrVector>,
    pub dma1_ch1: Option<IsrVector>,
    pub dma1_ch2: Option<IsrVector>,
    pub dma1_ch3: Option<IsrVector>,
    pub dma1_ch4: Option<IsrVector>,
    pub dma1_ch5: Option<IsrVector>,
    pub dma1_ch6: Option<IsrVector>,
    pub dma1_ch7: Option<IsrVector>,
    pub adc1: Option<IsrVector>,
    pub can1_tx: Option<IsrVector>,
    pub can1_rx0: Option<IsrVector>,
    pub can1_rx1: Option<IsrVector>,
    pub can1_sce: Option<IsrVector>,
    pub exti9_5: Option<IsrVector>,
    pub tim1_brk_tim15: Option<IsrVector>,
    pub tim1_up_tim16: Option<IsrVector>,
    pub tim1_trg_com: Option<IsrVector>,
    pub tim1_cc: Option<IsrVector>,
    pub tim2: Option<IsrVector>,
    _unavailable_tim3: Option<IsrVector>,
    _reserved_46: Option<IsrVector>,
    pub i2c1_ev: Option<IsrVector>,
    pub i2c1_er: Option<IsrVector>,
    _unavailable_i2c2_ev: Option<IsrVector>,
    _unavailable_i2c2_er: Option<IsrVector>,
    pub spi1: Option<IsrVector>,
    _unavailable_spi2: Option<IsrVector>,
    pub usart1: Option<IsrVector>,
    pub usart2: Option<IsrVector>,
    _unavailable_usart3: Option<IsrVector>,
    pub exti15_10: Option<IsrVector>,
    pub rtc_alarm: Option<IsrVector>,
    _reserved_58: Option<IsrVector>,
    _reserved_59: Option<IsrVector>,
    _reserved_60: Option<IsrVector>,
    _reserved_61: Option<IsrVector>,
    _reserved_62: Option<IsrVector>,
    _reserved_63: Option<IsrVector>,
    _reserved_64: Option<IsrVector>,
    _unavailable_sdmmc1: Option<IsrVector>,
    _reserved_66: Option<IsrVector>,
    pub spi3: Option<IsrVector>,
    _unavailable_uart4: Option<IsrVector>,
    _reserved_69: Option<IsrVector>,
    pub tim6_dac_under: Option<IsrVector>,
    pub tim7: Option<IsrVector>,
    pub dma2_ch1: Option<IsrVector>,
    pub dma2_ch2: Option<IsrVector>,
    pub dma2_ch3: Option<IsrVector>,
    pub dma2_ch4: Option<IsrVector>,
    pub dma2_ch5: Option<IsrVector>,
    _unavailable_dfsdm1_flt0: Option<IsrVector>,
    _unavailable_dfsdm1_flt1: Option<IsrVector>,
    _reserved_79: Option<IsrVector>,
    pub comp: Option<IsrVector>,
    pub lp_tim1: Option<IsrVector>,
    pub lp_tim2: Option<IsrVector>,
    pub usb_fs: Option<IsrVector>,
    pub dma2_ch6: Option<IsrVector>,
    pub dma2_ch7: Option<IsrVector>,
    pub lp_uart1: Option<IsrVector>,
    pub quad_spi: Option<IsrVector>,
    pub i2c3_ev: Option<IsrVector>,
    pub i2c3_er: Option<IsrVector>,
    pub sai1: Option<IsrVector>,
    _reserved_91: Option<IsrVector>,
    pub swpmi1: Option<IsrVector>,
    pub tsc: Option<IsrVector>,
    _unavailable_lcd: Option<IsrVector>,
    pub aes: Option<IsrVector>,
    pub rng: Option<IsrVector>,
    pub fpu: Option<IsrVector>,
    pub crs: Option<IsrVector>,
    _unavailable_i2c4_ev: Option<IsrVector>,
    _reserved_100: Option<IsrVector>
}

const _: () = {
    assert!(
        size_of::<IsrVectorTable>() == (85 * 4) + size_of::<CortexM4IsrVectorTable>(),
        "There must be 85 ISR vectors for the STM32L432KC, each 32-bits");

    assert!(align_of::<IsrVectorTable>() == 4, "Alignment of the ISR vector table must be 32-bits");
};

impl IsrVectorTable {
    pub const fn default() -> Self {
        Self {
            cortex_m4: CortexM4IsrVectorTable::default(),
            wwdg: None,
            pvd_pvm: None,
            rtc_tamp_css_lse: None,
            rtc_wkup: None,
            flash: None,
            rcc: None,
            exti0: None,
            exti1: None,
            exti2: None,
            exti3: None,
            exti4: None,
            dma1_ch1: None,
            dma1_ch2: None,
            dma1_ch3: None,
            dma1_ch4: None,
            dma1_ch5: None,
            dma1_ch6: None,
            dma1_ch7: None,
            adc1: None,
            can1_tx: None,
            can1_rx0: None,
            can1_rx1: None,
            can1_sce: None,
            exti9_5: None,
            tim1_brk_tim15: None,
            tim1_up_tim16: None,
            tim1_trg_com: None,
            tim1_cc: None,
            tim2: None,
            _unavailable_tim3: RESERVED_ISR_VECTOR,
            _reserved_46: RESERVED_ISR_VECTOR,
            i2c1_ev: None,
            i2c1_er: None,
            _unavailable_i2c2_ev: RESERVED_ISR_VECTOR,
            _unavailable_i2c2_er: RESERVED_ISR_VECTOR,
            spi1: None,
            _unavailable_spi2: RESERVED_ISR_VECTOR,
            usart1: None,
            usart2: None,
            _unavailable_usart3: RESERVED_ISR_VECTOR,
            exti15_10: None,
            rtc_alarm: None,
            _reserved_58: RESERVED_ISR_VECTOR,
            _reserved_59: RESERVED_ISR_VECTOR,
            _reserved_60: RESERVED_ISR_VECTOR,
            _reserved_61: RESERVED_ISR_VECTOR,
            _reserved_62: RESERVED_ISR_VECTOR,
            _reserved_63: RESERVED_ISR_VECTOR,
            _reserved_64: RESERVED_ISR_VECTOR,
            _unavailable_sdmmc1: RESERVED_ISR_VECTOR,
            _reserved_66: RESERVED_ISR_VECTOR,
            spi3: None,
            _unavailable_uart4: RESERVED_ISR_VECTOR,
            _reserved_69: RESERVED_ISR_VECTOR,
            tim6_dac_under: None,
            tim7: None,
            dma2_ch1: None,
            dma2_ch2: None,
            dma2_ch3: None,
            dma2_ch4: None,
            dma2_ch5: None,
            _unavailable_dfsdm1_flt0: RESERVED_ISR_VECTOR,
            _unavailable_dfsdm1_flt1: RESERVED_ISR_VECTOR,
            _reserved_79: RESERVED_ISR_VECTOR,
            comp: None,
            lp_tim1: None,
            lp_tim2: None,
            usb_fs: None,
            dma2_ch6: None,
            dma2_ch7: None,
            lp_uart1: None,
            quad_spi: None,
            i2c3_ev: None,
            i2c3_er: None,
            sai1: None,
            _reserved_91: RESERVED_ISR_VECTOR,
            swpmi1: None,
            tsc: None,
            _unavailable_lcd: RESERVED_ISR_VECTOR,
            aes: None,
            rng: None,
            fpu: None,
            crs: None,
            _unavailable_i2c4_ev: RESERVED_ISR_VECTOR,
            _reserved_100: RESERVED_ISR_VECTOR
        }
    }

    pub const fn with_default_unhandled(&self) -> Self {
        Self {
            cortex_m4: self.cortex_m4.with_default_unhandled(),
            wwdg: with_default_unhandled(self.wwdg),
            pvd_pvm: with_default_unhandled(self.pvd_pvm),
            rtc_tamp_css_lse: with_default_unhandled(self.rtc_tamp_css_lse),
            rtc_wkup: with_default_unhandled(self.rtc_wkup),
            flash: with_default_unhandled(self.flash),
            rcc: with_default_unhandled(self.rcc),
            exti0: with_default_unhandled(self.exti0),
            exti1: with_default_unhandled(self.exti1),
            exti2: with_default_unhandled(self.exti2),
            exti3: with_default_unhandled(self.exti3),
            exti4: with_default_unhandled(self.exti4),
            dma1_ch1: with_default_unhandled(self.dma1_ch1),
            dma1_ch2: with_default_unhandled(self.dma1_ch2),
            dma1_ch3: with_default_unhandled(self.dma1_ch3),
            dma1_ch4: with_default_unhandled(self.dma1_ch4),
            dma1_ch5: with_default_unhandled(self.dma1_ch5),
            dma1_ch6: with_default_unhandled(self.dma1_ch6),
            dma1_ch7: with_default_unhandled(self.dma1_ch7),
            adc1: with_default_unhandled(self.adc1),
            can1_tx: with_default_unhandled(self.can1_tx),
            can1_rx0: with_default_unhandled(self.can1_rx0),
            can1_rx1: with_default_unhandled(self.can1_rx1),
            can1_sce: with_default_unhandled(self.can1_sce),
            exti9_5: with_default_unhandled(self.exti9_5),
            tim1_brk_tim15: with_default_unhandled(self.tim1_brk_tim15),
            tim1_up_tim16: with_default_unhandled(self.tim1_up_tim16),
            tim1_trg_com: with_default_unhandled(self.tim1_trg_com),
            tim1_cc: with_default_unhandled(self.tim1_cc),
            tim2: with_default_unhandled(self.tim2),
            i2c1_ev: with_default_unhandled(self.i2c1_ev),
            i2c1_er: with_default_unhandled(self.i2c1_er),
            spi1: with_default_unhandled(self.spi1),
            usart1: with_default_unhandled(self.usart1),
            usart2: with_default_unhandled(self.usart2),
            exti15_10: with_default_unhandled(self.exti15_10),
            rtc_alarm: with_default_unhandled(self.rtc_alarm),
            spi3: with_default_unhandled(self.spi3),
            tim6_dac_under: with_default_unhandled(self.tim6_dac_under),
            tim7: with_default_unhandled(self.tim7),
            dma2_ch1: with_default_unhandled(self.dma2_ch1),
            dma2_ch2: with_default_unhandled(self.dma2_ch2),
            dma2_ch3: with_default_unhandled(self.dma2_ch3),
            dma2_ch4: with_default_unhandled(self.dma2_ch4),
            dma2_ch5: with_default_unhandled(self.dma2_ch5),
            comp: with_default_unhandled(self.comp),
            lp_tim1: with_default_unhandled(self.lp_tim1),
            lp_tim2: with_default_unhandled(self.lp_tim2),
            usb_fs: with_default_unhandled(self.usb_fs),
            dma2_ch6: with_default_unhandled(self.dma2_ch6),
            dma2_ch7: with_default_unhandled(self.dma2_ch7),
            lp_uart1: with_default_unhandled(self.lp_uart1),
            quad_spi: with_default_unhandled(self.quad_spi),
            i2c3_ev: with_default_unhandled(self.i2c3_ev),
            i2c3_er: with_default_unhandled(self.i2c3_er),
            sai1: with_default_unhandled(self.sai1),
            swpmi1: with_default_unhandled(self.swpmi1),
            tsc: with_default_unhandled(self.tsc),
            aes: with_default_unhandled(self.aes),
            rng: with_default_unhandled(self.rng),
            fpu: with_default_unhandled(self.fpu),
            crs: with_default_unhandled(self.crs),
            ..*self
        }
    }
}

#[macro_export]
macro_rules! define_isr_vector_table_from {
    ($isrs:expr) => {
        #[used]
        #[unsafe(link_section = ".smeg.isr_vector_table.st.stm32l432kc")]
        static _ISR_VECTOR_TABLE: $crate::interrupts::IsrVectorTable = const { $isrs }.with_default_unhandled();
    }
}
